# Generated by Django 5.0.6 on 2024-05-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndividualGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_code", models.CharField(max_length=3)),
                ("gameState", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
