# Generated by Django 5.0.6 on 2024-05-11 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="individualgame",
            old_name="game_code",
            new_name="gameCode",
        ),
    ]
