# Generated by Django 5.0.6 on 2024-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_rename_game_code_individualgame_gamecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualgame",
            name="board",
            field=models.JSONField(default=list, null=True),
        ),
    ]
