# Generated by Django 5.0.6 on 2024-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_individualgame_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualgame",
            name="board",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
