# Generated by Django 5.0 on 2024-05-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_alter_individualgame_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualgame",
            name="gameTurn",
            field=models.CharField(default="X", max_length=1, null=True),
        ),
    ]
