# Generated by Django 5.0 on 2024-05-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_individualgame_gameturn"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualgame",
            name="gameBoard",
            field=models.JSONField(null=True),
        ),
    ]
