# Generated by Django 5.0 on 2024-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_individualgame_gameboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualgame",
            name="gameBoard",
            field=models.JSONField(default={"Nothing": "Nothing"}, null=True),
        ),
    ]
