# Generated by Django 5.0 on 2024-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_alter_individualgame_gameboard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualgame",
            name="board",
        ),
        migrations.AlterField(
            model_name="individualgame",
            name="gameBoard",
            field=models.JSONField(
                default={"0": [0, 0, 0], "1": [0, 0, 0], "2": [0, 0, 0]}, null=True
            ),
        ),
    ]
