# Generated by Django 5.0 on 2024-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_remove_individualgame_board_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualgame",
            name="board",
            field=models.JSONField(max_length=3, null=True),
        ),
    ]
